/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-house-4-7b9d7d2a530648fe8ab096c9fba23be9
Title: Low poly house 4
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    PublicBuilding_4_Pack3_0: THREE.Mesh;
    Collider_Collider_0: THREE.Mesh;
  };
  materials: {
    Pack3: THREE.MeshStandardMaterial;
    Collider: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/low_poly_house_4.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_4_Pack3_0.geometry}
          material={materials.Pack3}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Collider_Collider_0.geometry}
          material={materials.Collider}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/low_poly_house_4.glb");
