/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {
  Mesh,
  MeshStandardMaterial,
  MeshBasicMaterial,
  Group,
  SphereGeometry,
  TextureLoader,
} from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { gsap } from "gsap";
import { useFrame, useLoader } from "@react-three/fiber";

export function Animals() {
  const fishMap = useLoader(TextureLoader, "/textures/fishMap.png");

  const waterRef = useRef<Mesh>(null!);
  const fishRef = useRef<Mesh>(null!);

  // Animation
  // if (unfloodPlanet) {
  //   gsap.to(waterRef.current.scale, {
  //     x: 1.2,
  //     y: 1.2,
  //     z: 1.2,
  //     duration: 3,
  //     delay: 2,
  //   });
  // }

  useFrame((_, delta) => {
    fishRef.current.rotateY(delta * 0.5);
    fishRef.current.rotateZ(delta * 0.05);
  });

  return (
    <>
      <group dispose={null}>
        {/* Water */}
        {/* <mesh>
          <sphereGeometry args={[1.6]} />
          <meshBasicMaterial
            map={fishMap}
            transparent
            opacity={0.5}
          />
        </mesh> */}
        <mesh ref={fishRef} renderOrder={4}>
          <sphereGeometry args={[1.006]} />
          <meshBasicMaterial
            map={fishMap}
            color={"black"}
            transparent
            opacity={0.1}
          />
        </mesh>
      </group>
    </>
  );
}
