/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Charlie Tinley (https://sketchfab.com/Tnkii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-bird-animated-82ada91f0ac64ab595fbc3dc994a3590
Title: Low Poly Bird (Animated)
*/

import * as THREE from "three";
import { useEffect, useMemo, useRef, type JSX } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { AnimationMixer } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    blinn2: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Take 001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Birds(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/low_poly_bird_animated.glb",
  ) as unknown as GLTFResult;
  const { ref, actions } = useAnimations(animations, group);
  // const mixer = useMemo(() => new AnimationMixer(), []);
  useEffect(() => {
    actions["Take 001"]?.play();
  }, []);

  const elapsedRef = useRef<number>(-Math.PI / 2);
  useFrame((_, delta) => {
    elapsedRef.current += delta * 0.5;
    if (ref.current) {
      ref.current.position.x = 1.4 * Math.cos(elapsedRef.current);
      ref.current.position.y = -1.4 * Math.sin(elapsedRef.current);
      // ref.current.rotation.y = elapsedRef.current * 2;
    }
  });
  return (
    <group
      ref={ref}
      {...props}
      dispose={null}
      scale={0.02}
      position={[0, 5, 0]}
      rotation={[0, Math.PI / 2, 0]}
    >
      <primitive object={nodes._rootJoint} />
      <skinnedMesh
        name="Object_7"
        geometry={nodes.Object_7.geometry}
        material={materials.blinn2}
        skeleton={nodes.Object_7.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/low_poly_bird_animated.glb");
