/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Charlie Tinley (https://sketchfab.com/Tnkii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-bird-animated-82ada91f0ac64ab595fbc3dc994a3590
Title: Low Poly Bird (Animated)
*/

import * as THREE from "three";
import { useEffect, useMemo, useRef, type JSX } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils, type GLTF } from "three-stdlib";
import { useFrame, useGraph } from "@react-three/fiber";
import { gsap } from "gsap";

// type GLTFResult = GLTF & {
//   nodes: {
//     Object_7: THREE.SkinnedMesh;
//     _rootJoint: THREE.Bone;
//   };
//   materials: {
//     blinn2: THREE.MeshStandardMaterial;
//   };
// };

type ActionName = "Take 001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

function Bird({
  orbitAxis,
  rotateBird,
}: {
  orbitAxis: string;
  rotateBird: [x: number, y: number, z: number];
}) {
  const group = useRef<THREE.Group>(null!);
  // const { nodes, materials, animations } = useGLTF(
  //   "/models/low_poly_bird_animated.glb",
  // ) as unknown as GLTFResult;

  const { scene, animations } = useGLTF("/models/low_poly_bird_animated.glb");

  const { ref, actions } = useAnimations(animations, group);

  //https://codesandbox.io/p/sandbox/k8phr?file=%2Fsrc%2FApp.js%3A18%2C21
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes, materials } = useGraph(clone);

  useEffect(() => {
    actions["Take 001"]?.play();
  }, []);

  const elapsedRef = useRef<number>(-Math.PI / 2);
  useFrame((_, delta) => {
    elapsedRef.current += delta * 0.5;
    if (ref.current) {
      if (orbitAxis === "z") {
        ref.current.rotation.z = elapsedRef.current * 0.8;
        ref.current.rotation.y = elapsedRef.current * 0.8;
      } else if (orbitAxis === "y") {
        ref.current.rotation.z = 0.5;
        ref.current.rotation.y = elapsedRef.current * 1.3 + 4;
      } else ref.current.rotation.x = elapsedRef.current;
    }
  });
  return (
    <group ref={ref} dispose={null}>
      <group scale={0.02} position={[0, 1.4, 0]} rotation={rotateBird}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.blinn2}
          skeleton={nodes.Object_7.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/low_poly_bird_animated.glb");

export function Birds({ addAnimals }: { addAnimals: boolean }) {
  const birdsRef = useRef<THREE.Group>(null!);
  if (addAnimals) {
    gsap.to(birdsRef.current.scale, {
      x: 1,
      y: 1,
      z: 1,
      duration: 1,
      delay: 2,
    });
  }
  return (
    <group ref={birdsRef} scale={0.7}>
      <Bird orbitAxis={"x"} rotateBird={[0, 0, 0]} />
      <Bird orbitAxis={"y"} rotateBird={[0, 0, 0]} />
      <Bird orbitAxis={"z"} rotateBird={[0, -Math.PI / 2, 0]} />
    </group>
  );
}
