import * as THREE from "three";
import React, { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { gsap } from "gsap";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-house-1-72b37584f1a74e66914d4c57ea7f70d8
Title: Low poly house 1
*/
type GLTFResultRedHouse = GLTF & {
  nodes: {
    PublicBuilding_7_Pack3_0: THREE.Mesh;
    Collider_PublicBuilding_7_Collider_0: THREE.Mesh;
  };
  materials: {
    Pack3: THREE.MeshStandardMaterial;
    Collider: THREE.MeshStandardMaterial;
  };
};

function RedHouse(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/low_poly_house_1.glb",
  ) as unknown as GLTFResultRedHouse;
  return (
    <group {...props} dispose={null}>
      <group scale={1} position={[0, 0, 0]} rotation={[0.6, 0.6, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0, 1.25, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.8, 0.96, 0]}
          rotation={[0.3, 0.5, -0.7]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[1.1, 0.5, -0.4]}
          rotation={[-0.5, 0.1, -1.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.5, 1.1, 0.3]}
          rotation={[0.4, 0.4, -0.4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.97, 0.72, 0.3]}
          rotation={[-0.5, -0.5, -1.2]}
        />
        {/* to modify */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.97, 0.72, 0.3]}
          rotation={[-0.5, -0.5, -1.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.97, 0.72, 0.3]}
          rotation={[-0.5, -0.5, -1.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.97, 0.72, 0.3]}
          rotation={[-0.5, -0.5, -1.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.97, 0.72, 0.3]}
          rotation={[-0.5, -0.5, -1.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_7_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.97, 0.72, 0.3]}
          rotation={[-0.5, -0.5, -1.2]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/low_poly_house_1.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-house-4-7b9d7d2a530648fe8ab096c9fba23be9
Title: Low poly house 4
*/

type GLTFResultOrangeHouse = GLTF & {
  nodes: {
    PublicBuilding_4_Pack3_0: THREE.Mesh;
    Collider_Collider_0: THREE.Mesh;
  };
  materials: {
    Pack3: THREE.MeshStandardMaterial;
    Collider: THREE.MeshStandardMaterial;
  };
};

function OrangeHouse(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/low_poly_house_4.glb",
  ) as unknown as GLTFResultOrangeHouse;
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.4, 0.2, -0.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_4_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0, 1.25, 0]}
          rotation={[0.1, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PublicBuilding_4_Pack3_0.geometry}
          material={materials.Pack3}
          scale={0.03}
          position={[0.9, 0.8, -0.3]}
          rotation={[0.2, 0.4, -0.9]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/low_poly_house_4.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fishboe (https://sketchfab.com/ministephen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-factory-a5e53371d0804162bd45cf05956da358
Title: Low Poly Factory
*/
type GLTFResultFactory = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    Factory: THREE.MeshStandardMaterial;
  };
};

function Factory(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/low_poly_factory.glb",
  ) as unknown as GLTFResultFactory;
  return (
    <group {...props} dispose={null} rotation={[0.4, 0, -0.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[0, 1.28, 0]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[0.1, 0.9, 0.9]}
        rotation={[0.7, 0, -0.1]}
        scale={0.02}
      />
      {/* to modify  */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[-0.5, 0.9, 0.75]}
        rotation={[0.9, -0.5, 0.5]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[0.5, 0.88, -0.8]}
        rotation={[-0.7, 0, -0.3]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[0.8, 0.97, -0.2]}
        rotation={[-0.2, 0, -0.7]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[1.22, -0.3, -0.3]}
        rotation={[0, 0.3, -1.6]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[-1, 0, -0.8]}
        rotation={[-0.5, -0.7, 1.3]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Factory}
        position={[-1.05, -0.2, 0.7]}
        rotation={[0.2, 0.6, 1.6]}
        scale={0.02}
      />
    </group>
  );
}

useGLTF.preload("/low_poly_factory.glb");

export function Buildings({ replaceBuildings }: { replaceBuildings: boolean }) {
  const housesRef = useRef<THREE.Group>(null!);
  const factoryRef = useRef<THREE.Group>(null!);

  //Animation
  if (replaceBuildings) {
    gsap.to(factoryRef.current.scale, {
      x: 0.5,
      y: 0.5,
      z: 0.5,
      duration: 3,
      delay: 2,
    });
    gsap.to(housesRef.current.scale, {
      x: 1,
      y: 1,
      z: 1,
      duration: 2,
      delay: 2,
    });
  }

  return (
    <>
      <group ref={housesRef} scale={0.5}>
        <RedHouse />
        <OrangeHouse />
      </group>
      <group ref={factoryRef}>
        <Factory />
      </group>
    </>
  );
}
