/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useFrame, useLoader } from "@react-three/fiber";
import {
  EffectComposer,
  Bloom,
  ToneMapping,
} from "@react-three/postprocessing";
import gsap from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    Cube021: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube021_2: THREE.Mesh;
    Cube021_3: THREE.Mesh;
    Plane: THREE.Mesh;
    Icosphere: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    Flame: THREE.MeshStandardMaterial;
    soil: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
};

export function Fire({ extinguishFire }: { extinguishFire: boolean }) {
  const fireRef = useRef<THREE.Group>(null!);
  const { nodes, materials } = useGLTF(
    "/models/fire.glb",
  ) as unknown as GLTFResult;
  const fireMaterial = new THREE.MeshStandardMaterial({
    color: "#ff3700",
    emissive: "#ff3700",
    emissiveIntensity: 10,
    transparent: true,
    opacity: 0.6,
  });

  let fixedScale = 1;
  const elapsedRef = useRef<number>(-Math.PI / 2);
  useFrame((_, delta) => {
    if (!extinguishFire) {
      elapsedRef.current += delta * 3;
      fireRef.current.scale.x =
        Math.sin(elapsedRef.current) * 0.02 + fixedScale;
      fireRef.current.scale.y =
        Math.sin(elapsedRef.current) * 0.02 + fixedScale;
      fireRef.current.scale.z =
        Math.sin(elapsedRef.current) * 0.02 + fixedScale;
    }
  });

  if (extinguishFire) {
    gsap.to(fireMaterial, {
      opacity: 0,
      duration: 2,
      delay: 2,
    });
  }

  return (
    <group dispose={null} ref={fireRef} scale={fixedScale}>
      <EffectComposer>
        <Bloom mipmapBlur luminanceThreshold={1} />
      </EffectComposer>
      <mesh
        position={[0.35, 1.2, 0]}
        rotation={[0, 0, -0.2]}
        scale={0.1}
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={fireMaterial}
      />
      <mesh
        position={[0.8, 0.96, 0]}
        rotation={[0.3, 0.5, -0.7]}
        scale={0.06}
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={fireMaterial}
      />
      <mesh
        position={[0, 1.1, 0.5]}
        rotation={[0.5, 0.5, 0]}
        scale={0.08}
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={fireMaterial}
      />
      <mesh
        position={[0.6, 1, -0.4]}
        rotation={[0.1, 0.7, -0.8]}
        scale={0.07}
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={fireMaterial}
      />
      <mesh
        position={[0.1, 0.6, 1]}
        rotation={[0.9, 0.5, -0.6]}
        scale={0.09}
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={fireMaterial}
      />
      <mesh
        position={[-1.05, -0.2, 0.6]}
        rotation={[0.5, 0.5, 1.2]}
        scale={0.06}
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={fireMaterial}
      />
      <mesh
        position={[-0.8, 0.55, -0.7]}
        rotation={[0, -1, 1]}
        scale={0.1}
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={fireMaterial}
      />
      <mesh
        position={[1.1, -0.3, -0.6]}
        rotation={[0, 0, -1.4]}
        scale={0.08}
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={fireMaterial}
      />
    </group>
  );
}

useGLTF.preload("/models/fire.glb");
