/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Mesh, Group, MeshStandardMaterial, AnimationAction } from "three";
import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { gsap } from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    ice: Mesh;
  };
  materials: {
    ["ice.001"]: MeshStandardMaterial;
  };
};

type ActionName = "ice|ice|Credit_card_earth.001Action.001";
type GLTFActions = Record<ActionName, AnimationAction>;

export function Ice({ meltIce }: { meltIce: boolean }) {
  const group = useRef<Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/ice.glb",
  ) as unknown as GLTFResult;
  // const { actions } = useAnimations<GLTFActions>(animations, group);
  const iceRef = useRef<Mesh>(null!);

  // Animation
  if (meltIce) {
    gsap.to(iceRef.current.scale, {
      x: 1,
      y: 1,
      z: 1,
      duration: 3,
      delay: 2,
    });
  }

  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <mesh
          ref={iceRef}
          name="ice"
          castShadow
          receiveShadow
          geometry={nodes.ice.geometry}
          material={materials["ice.001"]}
          position={[0, 0, 0]}
          rotation={[0, 0, 0]}
          scale={0.9}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ice.glb");
