/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    penguin: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshBasicMaterial;
  };
};

export function Penguin(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/penguin.glb") as unknown as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      position={[0, -1.24, 0]}
      rotation={[Math.PI, Math.PI, 0]}
      scale={0.09}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.penguin.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.penguin.geometry}
        material={materials.Material}
        position={[2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.penguin.geometry}
        material={materials.Material}
        position={[0, -0.3, 3]}
      />
    </group>
  );
}

useGLTF.preload("/penguin.glb");
