/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Mesh, MeshStandardMaterial, Group, SphereGeometry } from "three";
import React, { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { gsap } from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    Earth_1: Mesh;
    Earth_2: Mesh;
    mountains1: Mesh;
    Mesh002: Mesh;
    Mesh002_1: Mesh;
    mountains3: Mesh;
  };
  materials: {
    earth: MeshStandardMaterial;
    sand: MeshStandardMaterial;
    mountain3: MeshStandardMaterial;
    ice2: MeshStandardMaterial;
    mountain: MeshStandardMaterial;
    mountain2: MeshStandardMaterial;
  };
};

export function Planet({ floodPlanet }: { floodPlanet: boolean }) {
  const { nodes, materials } = useGLTF("/surface.glb") as unknown as GLTFResult;

  const containerRef = useRef<Group>(null!);
  const waterRef = useRef<Mesh>(null!);
  const terrainRef = useRef<Mesh>(null!);

  // Animation
  if (floodPlanet) {
    gsap.to(waterRef.current.scale, {
      x: 1.27,
      y: 1.27,
      z: 1.27,
      duration: 3,
      delay: 1,
    });
  }

  return (
    <>
      <group dispose={null}>
        Water
        <mesh
          ref={waterRef}
          castShadow
          receiveShadow
          geometry={new SphereGeometry()}
          // material={materials["Material.009"]}
          // onClick={waterRise}
          scale={1.2}
          material={new MeshStandardMaterial({ color: "lightblue" })}
        />
        <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Earth_1.geometry}
            material={materials.earth}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Earth_2.geometry}
            material={materials.sand}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mountains1.geometry}
          material={materials.mountain3}
          position={[0, 0, 0]}
          rotation={[0, 0, 0]}
        />
        <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002.geometry}
            material={materials.ice2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_1.geometry}
            material={materials.mountain}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mountains3.geometry}
          material={materials.mountain2}
          position={[0, 0, 0]}
          rotation={[0, 0, 0]}
        />
      </group>
    </>
  );
}

useGLTF.preload("/surface.glb");
