/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: danhoallia17 (https://sketchfab.com/danhoallia17)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eolienne-570bc8c6a39940efbd0c529b85904e20
Title: Éolienne
*/

import * as THREE from "three";
import { useEffect, useMemo, useRef, type JSX } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils, type GLTF } from "three-stdlib";
import { whiteMaterial } from "../reusables/materials";
import { useGraph } from "@react-three/fiber";
import { gsap } from "gsap";

// type GLTFResult = GLTF & {
//   nodes: {
//     Object_49: THREE.SkinnedMesh;
//     Object_76: THREE.SkinnedMesh;
//     Object_79: THREE.SkinnedMesh;
//     Object_94: THREE.SkinnedMesh;
//     GLTF_created_0_rootJoint: THREE.Bone;
//   };
// };

type ActionName = "idle" | "idle_with_cross_section";
// type GLTFActions = Record<ActionName, THREE.AnimationAction>

function WindTurbine(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null!);
  // const { nodes, animations } = useGLTF(
  //   "/models/eolienne.glb",
  // ) as unknown as GLTFResult;

  const { scene, animations } = useGLTF("/models/eolienne.glb");

  //https://codesandbox.io/p/sandbox/k8phr?file=%2Fsrc%2FApp.js%3A18%2C21
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);

  const { actions } = useAnimations<THREE.AnimationClip>(animations, group);
  useEffect(() => {
    actions["idle"]?.play();
  }, []);

  return (
    <group
      ref={group}
      dispose={null}
      position={[-1.05, -0.05, 0.3]}
      rotation={[-Math.PI / 2, 0, 1.9]}
      {...props}
    >
      <group scale={0.005}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_49"
          geometry={nodes.Object_49.geometry}
          material={whiteMaterial}
          skeleton={nodes.Object_49.skeleton}
        />
        <skinnedMesh
          name="Object_76"
          geometry={nodes.Object_76.geometry}
          material={whiteMaterial}
          skeleton={nodes.Object_76.skeleton}
        />
        <skinnedMesh
          name="Object_79"
          geometry={nodes.Object_79.geometry}
          material={whiteMaterial}
          skeleton={nodes.Object_79.skeleton}
        />
        <skinnedMesh
          name="Object_94"
          geometry={nodes.Object_94.geometry}
          material={whiteMaterial}
          skeleton={nodes.Object_94.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/eolienne.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: antonmoek (https://sketchfab.com/antonmoek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-low-poly-solar-panel-5a3a5a0b073044af8b388cb494ff0869
Title: Cartoon Low Poly Solar Panel
*/

type GLTFResult = GLTF & {
  nodes: {
    Plane_Environment_0: THREE.Mesh;
    Cylinder_Environment1_0: THREE.Mesh;
    Plane_003_Environment2_0: THREE.Mesh;
  };
  materials: {
    Environment: THREE.MeshStandardMaterial;
    ["Environment.1"]: THREE.MeshStandardMaterial;
    ["Environment.2"]: THREE.MeshStandardMaterial;
  };
};

function SolarPanel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/cartoon_low_poly_solar_panel.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_003_Environment2_0.geometry}
        material={materials["Environment.2"]}
        scale={0.0005}
        position={[-1.08, 0.73, 0]}
        rotation={[-1.1, -1.18, 2.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_003_Environment2_0.geometry}
        material={materials["Environment.2"]}
        scale={0.0005}
        position={[0.9, 0.82, -0.4]}
        rotation={[-0.5, 0.9, 2.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_003_Environment2_0.geometry}
        material={materials["Environment.2"]}
        scale={0.0005}
        position={[0.5, 1.15, -0.5]}
        rotation={[-0.6, 0.5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_003_Environment2_0.geometry}
        material={materials["Environment.2"]}
        scale={0.0005}
        position={[0.45, 1.05, -0.65]}
        rotation={[-0.9, 0.5, 2.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_003_Environment2_0.geometry}
        material={materials["Environment.2"]}
        scale={0.0005}
        position={[0.35, 1.15, -0.6]}
        rotation={[-0.9, 0.5, 2.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_003_Environment2_0.geometry}
        material={materials["Environment.2"]}
        scale={0.0005}
        position={[0.07, 1.17, 0.55]}
        rotation={[-0.5, 0.5, 3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_003_Environment2_0.geometry}
        material={materials["Environment.2"]}
        scale={0.0005}
        position={[0.4, 0.6, 1.1]}
        rotation={[-0.5, 0, 2.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_003_Environment2_0.geometry}
        material={materials["Environment.2"]}
        scale={0.0005}
        position={[0.25, 0.6, 1.1]}
        rotation={[-0.5, 0, 2.5]}
      />
    </group>
  );
}

useGLTF.preload("/models/cartoon_low_poly_solar_panel.glb");

export function RenewableEnergy({
  transitionEnergy,
}: {
  transitionEnergy: boolean;
}) {
  const renewablesRef = useRef<THREE.Group>(null!);

  //Animation
  if (transitionEnergy) {
    gsap.to(renewablesRef.current.scale, {
      x: 1,
      y: 1,
      z: 1,
      duration: 3,
      delay: 2,
    });
  }
  return (
    <group ref={renewablesRef} scale={0.5}>
      <WindTurbine />
      <WindTurbine position={[-0.98, -0.2, 0.4]} />
      <WindTurbine position={[-1.05, -0.2, 0.1]} />

      <WindTurbine position={[0.65, 0.8, 0.4]} rotation={[0.6, 0.4, -0.5]} />
      <WindTurbine position={[0.8, 0.7, 0.4]} rotation={[0.6, 0.4, -0.5]} />
      <WindTurbine position={[0.6, 0.7, 0.55]} rotation={[0.6, 0.4, -0.5]} />

      <WindTurbine position={[0.4, -0.1, 1]} rotation={[3, 1.2, -1.5]} />
      <WindTurbine position={[0.5, 0.1, 1]} rotation={[3, 1.2, -1.5]} />

      <WindTurbine position={[0.95, -0.15, -0.5]} rotation={[-2.4, 3, 1]} />

      <SolarPanel />
    </group>
  );
}
