/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Group, Mesh, MeshPhysicalMaterial } from "three";
import { useRef, type JSX } from "react";
import { useGLTF, Html } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { gsap } from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    Earth002: Mesh;
    Earth002_1: Mesh;
  };
  materials: {
    Trunk: MeshPhysicalMaterial;
    Leafs: MeshPhysicalMaterial;
  };
};

export function Trees({ growTrees }: { growTrees: boolean }) {
  const { nodes, materials } = useGLTF("/arbres.glb") as unknown as GLTFResult;
  const deadTreeRef = useRef<Mesh>(null!);
  const treeRef = useRef<Mesh>(null!);
  const containerRef = useRef<Group>(null!);
  const leavesRef = useRef<Mesh>(null!);

  //Animation
  if (growTrees) {
    gsap.to(deadTreeRef.current.scale, {
      x: 0.5,
      y: 0.5,
      z: 0.5,
      duration: 3,
      delay: 2,
    });
    gsap.to(treeRef.current.scale, { x: 1, y: 1, z: 1, duration: 2, delay: 2 });
    // gsap.to(leavesRef.current.scale, { x: 1, y: 1, z: 1, duration: 2 });
  }
  return (
    <group dispose={null}>
      <group
        ref={treeRef}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={0.5}
      >
        {/* Trunk */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Earth002.geometry}
          material={materials.Trunk}
        />
        {/* Leaves */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Earth002_1.geometry}
          material={materials.Leafs}
          ref={leavesRef}
          // scale={0}
        />
      </group>
      <group ref={deadTreeRef} position={[0, 0, 0]} rotation={[0, 0, 0]}>
        {/* Trunk */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Earth002.geometry}
          material={materials.Trunk}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/arbres.glb");
