import * as THREE from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { gsap } from "gsap";
import { grayMaterial, blackMaterial } from "../reusables/materials";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Emil Gilmutdinov (https://sketchfab.com/Emil_Gilmutdinov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fuel-barrel-55f313a9dfee4946b0a0dcb59704c2cb
Title: Fuel Barrel
*/

type GLTFResult = GLTF & {
  nodes: {
    FuelBarrel_Low_FuelBarrel_0: THREE.Mesh;
  };
  materials: {
    FuelBarrel: THREE.MeshStandardMaterial;
  };
};

function FuelBarrel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/fuel_barrel.glb",
  ) as unknown as GLTFResult;
  const barrelRef = useRef<THREE.Group>(null!);

  return (
    <group {...props} dispose={null} ref={barrelRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0, 1.2, 0]}
        rotation={[1, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.5, 1.15, 0]}
        rotation={[-1.5, 0.5, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-1, 0.6, 0.5]}
        rotation={[-1, 0.8, -0.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0.3, -1.28, 0]}
        rotation={[1, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0.25, -1.25, 0]}
        rotation={[1.7, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0, 0.1, -1.27]}
        rotation={[0.6, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0.5, 0.4, -1.05]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0.9, -0.6, 0.8]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0, -0.2, 1.25]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0, -0.9, -0.9]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.7, -1, -0.3]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.7, -1, -0.3]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.7, 0, -1]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.6, 0.3, -1]}
        rotation={[0, 0, -0.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[1, -0.7, -0.1]}
        rotation={[0, 0, -0.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[1.18, -0.2, 0.3]}
        rotation={[0, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.7, -0.9, 0.6]}
        rotation={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/fuel_barrel.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: daniel.2U (https://sketchfab.com/daniel.2U)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trash-can-and-garbage-bag-low-poly-63cdc7dbfa8741d7b65a856f7acca148
Title: Trash Can and Garbage Bag low poly
*/

type GLTFResultTrash = GLTF & {
  nodes: {
    Cylinder597_Material036_0: THREE.Mesh;
    Cylinder597_Material037_0: THREE.Mesh;
  };
};

function Trash(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/trash_can_and_garbage_bag_low_poly.glb",
  ) as unknown as GLTFResultTrash;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -1.37, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.2}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder597_Material036_0.geometry}
          material={grayMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder597_Material037_0.geometry}
          material={blackMaterial}
        />
      </group>
      <group
        position={[0.6, -1.1, 0]}
        rotation={[Math.PI / 3, 0, 0]}
        scale={0.2}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder597_Material036_0.geometry}
          material={grayMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder597_Material037_0.geometry}
          material={blackMaterial}
        />
      </group>
      <group position={[0.9, 0.7, 0.5]} rotation={[-1, 0, 0]} scale={0.2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder597_Material036_0.geometry}
          material={grayMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder597_Material037_0.geometry}
          material={blackMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/trash_can_and_garbage_bag_low_poly.glb");

export function Waste({ cleanWaste }: { cleanWaste: boolean }) {
  const wasteRef = useRef<THREE.Group>(null!);

  //Animation
  if (cleanWaste) {
    gsap.to(wasteRef.current.scale, {
      x: 0.5,
      y: 0.5,
      z: 0.5,
      duration: 3,
      delay: 2,
    });
  }

  return (
    <group ref={wasteRef}>
      <FuelBarrel />
      <Trash />
    </group>
  );
}
