/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Emil Gilmutdinov (https://sketchfab.com/Emil_Gilmutdinov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fuel-barrel-55f313a9dfee4946b0a0dcb59704c2cb
Title: Fuel Barrel
*/

import * as THREE from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import { gsap } from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    FuelBarrel_Low_FuelBarrel_0: THREE.Mesh;
  };
  materials: {
    FuelBarrel: THREE.MeshStandardMaterial;
  };
};

function FuelBarrel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/fuel_barrel.glb",
  ) as unknown as GLTFResult;
  const barrelRef = useRef<THREE.Group>(null!);

  return (
    <group {...props} dispose={null} ref={barrelRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0, 1.2, 0]}
        rotation={[1, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.5, 1.15, 0]}
        rotation={[-1.5, 0.5, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-1, 0.6, 0.5]}
        rotation={[-1, 0.8, -0.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0.3, -1.28, 0]}
        rotation={[1, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0.25, -1.25, 0]}
        rotation={[1.7, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0, 0.1, -1.27]}
        rotation={[0.6, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0.5, 0.4, -1.05]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0.9, -0.6, 0.8]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0, -0.2, 1.25]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[0, -0.9, -0.9]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.7, -1, -0.3]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-0.7, -1, -0.3]}
        rotation={[0, 0, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FuelBarrel_Low_FuelBarrel_0.geometry}
        material={materials.FuelBarrel}
        scale={0.001}
        position={[-1.5, -1, -0.3]}
        rotation={[0, 0, 1]}
      />
    </group>
  );
}

useGLTF.preload("/fuel_barrel.glb");

export function Waste({ cleanWaste }: { cleanWaste: boolean }) {
  const wasteRef = useRef<THREE.Group>(null!);

  //Animation
  if (cleanWaste) {
    gsap.to(wasteRef.current.scale, {
      x: 0.5,
      y: 0.5,
      z: 0.5,
      duration: 3,
      delay: 1,
    });
  }

  return (
    <group ref={wasteRef}>
      <FuelBarrel />
    </group>
  );
}
