/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Mesh, Group, MeshBasicMaterial } from "three";
import { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import gsap from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    penguin: Mesh;
  };
  materials: {
    Material: MeshBasicMaterial;
  };
};

export function Penguin({ unmeltIce }: { unmeltIce: boolean }) {
  const { nodes, materials } = useGLTF("/penguin.glb") as unknown as GLTFResult;

  const penguinsRef = useRef<Group>(null!);

  // Animation;
  if (unmeltIce) {
    gsap.to(penguinsRef.current.position, {
      x: 0,
      y: -1.24,
      z: 0,
      duration: 3,
      delay: 3,
    });
  }

  return (
    <group
      ref={penguinsRef}
      dispose={null}
      position={[0, 0, 0]}
      rotation={[Math.PI, Math.PI, 0]}
      scale={0.09}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.penguin.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.penguin.geometry}
        material={materials.Material}
        position={[2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.penguin.geometry}
        material={materials.Material}
        position={[0, -0.3, 3]}
      />
    </group>
  );
}

useGLTF.preload("/penguin.glb");
