/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { gsap } from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    Cube001_1: THREE.Mesh;
    Cube001_2: THREE.Mesh;
    Cube001_3: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
  };
};

export function PolarBear({
  unmeltIce,
  addAnimals,
}: {
  unmeltIce: boolean;
  addAnimals: boolean;
}) {
  const { nodes, materials } = useGLTF(
    "/models/polar-bear.glb",
  ) as unknown as GLTFResult;

  const polarBearsRef = useRef<THREE.Group>(null!);

  if (addAnimals) {
    gsap.to(polarBearsRef.current.scale, {
      x: 1,
      y: 1,
      z: 1,
      duration: 1,
      delay: 2,
    });
  }

  if (unmeltIce) {
    gsap.to(polarBearsRef.current.position, {
      y: 0,
      duration: 2,
      delay: 2,
    });
  }
  return (
    <group
      ref={polarBearsRef}
      dispose={null}
      position={[0, -1, 0]}
      rotation={[0, 0, 0.3]}
      scale={0.8}
    >
      <group
        scale={0.04}
        position={[0.2, 1.2, -0.2]}
        rotation={[-0.2, 0, -0.1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group scale={0.04} position={[0.1, 1.26, 0]} rotation={[0, 1, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials["Material.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/polar-bear.glb");
